import { Product } from "../types";

export const mockProducts: Product[] = [
  {
    id: "prod_1",
    name: "Midnight Oasis",
    brand: "Lumière Noire",
    description: "Zmysłowy, ciemny zapach z nutami drzewa agarowego i czarnej róży. Idealny na wieczorne wyjścia.",
    price: 890,
    imageUrl: "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=600&auto=format&fit=crop",
    notes: ["Drzewo Agarowe (Oud)", "Czarna Róża", "Paczula", "Bursztyn"],
    gender: "Unisex",
  },
  {
    id: "prod_2",
    name: "Aura d'Or",
    brand: "Maison Dorée",
    description: "Promienny, ciepły zapach z intensywnymi nutami wanilii z Madagaskaru i jaśminu.",
    price: 1250,
    imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=600&auto=format&fit=crop",
    notes: ["Wanilia z Madagaskaru", "Jaśmin", "Bergamotka"],
    gender: "Damskie",
  },
  {
    id: "prod_3",
    name: "Vétiver Impérial",
    brand: "Atelier du Bois",
    description: "Klasyczna elegancja zamknięta we flakonie. Chłodny wetiwer w połączeniu z cytrusami.",
    price: 650,
    imageUrl: "https://images.unsplash.com/photo-1595425959632-14eb023366bc?q=80&w=600&auto=format&fit=crop",
    notes: ["Wetiwer", "Grejpfrut", "Pieprz Różowy", "Mech Dębowy"],
    gender: "Męskie",
  },
  {
    id: "prod_4",
    name: "Santal Velours",
    brand: "Lumière Noire",
    description: "Kremowe drzewo sandałowe i przyprawy. Zapach, który otula niczym luksusowy aksamit.",
    price: 1050,
    imageUrl: "https://images.unsplash.com/photo-1615397347454-00e28f2ab1bd?q=80&w=600&auto=format&fit=crop",
    notes: ["Drzewo Sandałowe", "Kardamon", "Irys"],
    gender: "Unisex",
  },
  {
    id: "prod_5",
    name: "Fleur de La Lune",
    brand: "Elixir De Nuit",
    description: "Kwiatowy zapach z akordem białych kwiatów rozkwitających nocą. Niezwykle zmysłowy.",
    price: 920,
    imageUrl: "https://images.unsplash.com/photo-1588612140409-e85df6495be2?q=80&w=600&auto=format&fit=crop",
    notes: ["Tuberoza", "Kwiat Pomarańczy", "Białe Piżmo"],
    gender: "Damskie",
  },
  {
    id: "prod_6",
    name: "Cuir Ébène",
    brand: "Atelier du Bois",
    description: "Wyrazisty zapach, łączący surową skórę z tytoniem i głębokimi nutami drzewnymi.",
    price: 800,
    imageUrl: "https://images.unsplash.com/photo-1594035678438-fb9e2d36ddbc?q=80&w=600&auto=format&fit=crop",
    notes: ["Skóra", "Tytoń", "Cedr", "Szafran"],
    gender: "Męskie",
  }
];
